/**
 * search.relevance.test.ts — the search quality regression suite (#611).
 *
 * Runs entirely offline against a committed fixture of real model output
 * (search-fixtures.json, generated by scripts/gen-search-fixtures.ts from
 * fixtures/corpus.ts) — no embedding model calls in CI. It exercises the
 * exact same ranking logic as search.service.ts (keyword + vector + RRF +
 * exact-match promotion), just fed precomputed vectors instead of live ones.
 *
 * This is the artifact that stops a future change from silently making
 * search worse: any refactor of hybrid.ts/vector-store.ts must keep clearing
 * these thresholds.
 */
import { readFileSync } from 'fs';
import path from 'path';
import { describe, expect, it } from 'vitest';
import { FIXTURE_DATASETS, FIXTURE_QUERIES } from './fixtures/corpus';
import {
  findExactMatchId,
  keywordSearch,
  reciprocalRankFusion,
  type KeywordDocument,
} from './hybrid';
import { topKBySimilarity } from './vector-store';

interface FixtureFile {
  model: string;
  dims: number;
  datasets: { id: string; vector: number[] }[];
  queries: { query: string; expectedDatasetId: string; vector: number[] }[];
}

const FIXTURE_PATH = path.resolve(__dirname, 'fixtures/search-fixtures.json');
const fixture: FixtureFile = JSON.parse(readFileSync(FIXTURE_PATH, 'utf8'));

// Regression floors — set from this suite's actual measured performance
// (recall@5 = 29/30 = 0.967, mean nDCG@5 = 0.909 at time of writing) with a
// margin below both, not an aspirational target. A drop below these means a
// change genuinely regressed ranking quality; tightening them is fine, but
// do it deliberately after confirming the new numbers, not by loosening on CI failure.
const MIN_RECALL_AT_5 = 0.93;
const MIN_MEAN_NDCG_AT_5 = 0.85;

function keywordDocs(): KeywordDocument[] {
  return FIXTURE_DATASETS.map(d => ({
    datasetId: d.id,
    name: d.name,
    description: d.description,
    category: d.category,
    type: d.type,
    tags: d.tags,
  }));
}

function fixtureQueryVector(query: string): number[] {
  const entry = fixture.queries.find(q => q.query === query);
  if (!entry) throw new Error(`No fixture vector for query "${query}" — regenerate the fixture`);
  return entry.vector;
}

/** Reproduces search.service.ts's ranking pipeline against fixture vectors. */
function rankForQuery(queryText: string): string[] {
  const docs = keywordDocs();
  const keywordResults = keywordSearch(queryText, docs);
  const vectorEntries = fixture.datasets.map(d => ({
    datasetId: d.id,
    vector: Float32Array.from(d.vector),
  }));
  const queryVector = Float32Array.from(fixtureQueryVector(queryText));
  const vectorResults = topKBySimilarity(vectorEntries, queryVector, 100);

  const fused = reciprocalRankFusion([keywordResults, vectorResults]);
  const exactId = findExactMatchId(queryText, docs);
  if (!exactId) return fused.map(r => r.datasetId);

  const rest = fused.filter(r => r.datasetId !== exactId);
  return [exactId, ...rest.map(r => r.datasetId)];
}

/** DCG@k for a single relevant document (binary relevance) — IDCG@k is always 1. */
function dcgAt(rankedIds: string[], relevantId: string, k: number): number {
  const idx = rankedIds.slice(0, k).indexOf(relevantId);
  return idx === -1 ? 0 : 1 / Math.log2(idx + 2);
}

describe('search relevance regression suite', () => {
  it('fixture is fresh: every corpus dataset/query has a committed vector (run npm run gen:search-fixtures if this fails)', () => {
    const fixtureDatasetIds = new Set(fixture.datasets.map(d => d.id));
    for (const d of FIXTURE_DATASETS) {
      expect(fixtureDatasetIds.has(d.id), `missing fixture vector for dataset ${d.id}`).toBe(true);
    }
    const fixtureQueries = new Set(fixture.queries.map(q => q.query));
    for (const q of FIXTURE_QUERIES) {
      expect(fixtureQueries.has(q.query), `missing fixture vector for query "${q.query}"`).toBe(
        true,
      );
    }
  });

  it('ACCEPTANCE: "large holder activity" returns the whale dataset in the top 3 despite zero shared keywords', () => {
    const query = 'large holder activity';
    const ranked = rankForQuery(query);
    expect(ranked.slice(0, 3)).toContain('ds-whale-wallets');

    // Prove this is genuinely a semantic win, not an accident of the keyword
    // arm: the keyword-only ranking must NOT have found it at all.
    const keywordOnly = keywordSearch(query, keywordDocs());
    expect(keywordOnly.find(r => r.datasetId === 'ds-whale-wallets')).toBeUndefined();
  });

  const exactMatchQueries = FIXTURE_QUERIES.filter(q => q.note.includes('exact'));
  it(`ACCEPTANCE: has at least 4 exact-match fixture queries to test (found ${exactMatchQueries.length})`, () => {
    expect(exactMatchQueries.length).toBeGreaterThanOrEqual(4);
  });

  it.each(exactMatchQueries)(
    'ACCEPTANCE: exact match "$query" ranks first',
    ({ query, expectedDatasetId }) => {
      const ranked = rankForQuery(query);
      expect(ranked[0]).toBe(expectedDatasetId);
    },
  );

  it(`recall@5 across all ${FIXTURE_QUERIES.length} labelled queries meets the regression floor`, () => {
    const misses: string[] = [];
    for (const q of FIXTURE_QUERIES) {
      const ranked = rankForQuery(q.query);
      if (!ranked.slice(0, 5).includes(q.expectedDatasetId)) misses.push(q.query);
    }
    const recallAt5 = (FIXTURE_QUERIES.length - misses.length) / FIXTURE_QUERIES.length;
    expect(recallAt5, `misses: ${misses.join(', ')}`).toBeGreaterThanOrEqual(MIN_RECALL_AT_5);
  });

  it('mean nDCG@5 across all labelled queries meets the regression floor', () => {
    let total = 0;
    for (const q of FIXTURE_QUERIES) {
      const ranked = rankForQuery(q.query);
      total += dcgAt(ranked, q.expectedDatasetId, 5);
    }
    const meanNdcg = total / FIXTURE_QUERIES.length;
    expect(meanNdcg).toBeGreaterThanOrEqual(MIN_MEAN_NDCG_AT_5);
  });
});
