/**
 * artifacts.ts — what provisioning hands back.
 *
 * Rendering is split from writing so both formats are gate-testable as pure
 * string/object transforms. Determinism matters here too: the acceptance
 * criterion is byte-identical output across resets, so nothing in this file may
 * embed a timestamp, a random id, or a map iteration order that can vary.
 */

import { writeFile } from 'node:fs/promises';
import type { DevnetAccount } from './accounts.ts';
import { PLATFORM_FEE_BPS, TOKEN_DECIMALS, USDC_CODE } from './config.ts';

export interface ProvisionResult {
  passphrase: string;
  horizonUrl: string;
  rpcUrl: string;
  friendbotUrl: string;
  contractId: string;
  wasmHash: string;
  usdcSacAddress: string;
  xlmSacAddress: string;
  issuerPublicKey: string;
  accounts: DevnetAccount[];
  balances: Record<string, { xlm: number; usdc: number; trustline: boolean }>;
  datasetIds: string[];
}

/**
 * Renders `.env.devnet`.
 *
 * Deliberately a complete file, not a fragment: a contributor copies it to
 * `backend/.env` and the backend runs against the devnet with no further edits.
 * Secrets are included because every one of them is a throwaway key for a
 * throwaway local network — the file header says so, and .gitignore keeps it out
 * of commits regardless.
 */
export function renderEnvFile(result: ProvisionResult): string {
  const byRole = Object.fromEntries(result.accounts.map(a => [a.role, a]));
  const lines: string[] = [
    '# ─────────────────────────────────────────────────────────────',
    '# .env.devnet — GENERATED by `npm run devnet`. Do not edit by hand.',
    '#',
    '# Every key below belongs to an ephemeral local Stellar network that is',
    '# destroyed by `npm run devnet:reset`. They are deterministic, public,',
    '# identical for every contributor, and worthless. Never reuse them on',
    '# testnet or mainnet.',
    '#',
    '# Usage:  cp .env.devnet backend/.env  &&  npm run dev',
    '# ─────────────────────────────────────────────────────────────',
    '',
    '# ── Network ──────────────────────────────────────────────────',
    'STELLAR_NETWORK=devnet',
    `STELLAR_NETWORK_PASSPHRASE=${result.passphrase}`,
    `STELLAR_HORIZON_URL=${result.horizonUrl}`,
    `SOROBAN_RPC_URL=${result.rpcUrl}`,
    `STELLAR_FRIENDBOT_URL=${result.friendbotUrl}`,
    '',
    '# ── Escrow contract ──────────────────────────────────────────',
    `ESCROW_CONTRACT_ID=${result.contractId}`,
    `ESCROW_WASM_HASH=${result.wasmHash}`,
    `PLATFORM_FEE_RATE=${PLATFORM_FEE_BPS / 10_000}`,
    `PLATFORM_FEE_BPS=${PLATFORM_FEE_BPS}`,
    '',
    '# ── Devnet USDC ──────────────────────────────────────────────',
    `USDC_ISSUER=${result.issuerPublicKey}`,
    `USDC_SAC_ADDRESS=${result.usdcSacAddress}`,
    `XLM_SAC_ADDRESS=${result.xlmSacAddress}`,
    `USDC_ASSET_CODE=${USDC_CODE}`,
    `USDC_DECIMALS=${TOKEN_DECIMALS}`,
    '',
    '# ── Accounts (public) ────────────────────────────────────────',
  ];

  for (const account of result.accounts) {
    lines.push(`# ${account.role}: ${account.description}`);
    lines.push(`${account.envKey}=${account.publicKey}`);
  }

  lines.push('', '# ── Accounts (secret — throwaway devnet keys) ────────────────');
  for (const account of result.accounts) {
    lines.push(`${account.envKey.replace(/_PUBLIC$/, '_SECRET')}=${account.secret}`);
  }

  lines.push(
    '',
    '# ── Backend wiring ───────────────────────────────────────────',
    '# The backend signs release/refund as the contract admin.',
    `AGENT_WALLET_SECRET=${byRole.admin.secret}`,
    `ESCROW_WALLET=${byRole.admin.publicKey}`,
    `TREASURY_ADDRESS=${byRole.treasury.publicKey}`,
    `ARBITRATOR_ADDRESS=${byRole.arbitrator.publicKey}`,
    '',
    '# ── Local API config ─────────────────────────────────────────',
    'PORT=3001',
    'FRONTEND_URL=http://localhost:5173',
    'DATABASE_URL=file:./data/devnet.db',
    'API_KEY=devnet_api_key',
    'ADMIN_API_KEY=devnet_admin_key',
    'SELLER_JWT_SECRET=devnet_jwt_secret',
    'PAYMENT_WEBHOOK_SECRET=devnet_webhook_secret',
    '',
  );
  return lines.join('\n');
}

export interface AccountsFile {
  network: {
    name: 'devnet';
    passphrase: string;
    horizonUrl: string;
    rpcUrl: string;
    friendbotUrl: string;
  };
  contract: { escrowContractId: string; wasmHash: string; platformFeeBps: number };
  asset: {
    code: string;
    issuer: string;
    decimals: number;
    sacAddress: string;
    xlmSacAddress: string;
  };
  accounts: Array<{
    role: string;
    publicKey: string;
    secret: string;
    trustline: boolean;
    description: string;
    balances: { xlm: number; usdc: number };
  }>;
  datasets: string[];
}

/** Builds `devnet.accounts.json` — the machine-readable twin of the summary. */
export function renderAccountsFile(result: ProvisionResult): AccountsFile {
  return {
    network: {
      name: 'devnet',
      passphrase: result.passphrase,
      horizonUrl: result.horizonUrl,
      rpcUrl: result.rpcUrl,
      friendbotUrl: result.friendbotUrl,
    },
    contract: {
      escrowContractId: result.contractId,
      wasmHash: result.wasmHash,
      platformFeeBps: PLATFORM_FEE_BPS,
    },
    asset: {
      code: USDC_CODE,
      issuer: result.issuerPublicKey,
      decimals: TOKEN_DECIMALS,
      sacAddress: result.usdcSacAddress,
      xlmSacAddress: result.xlmSacAddress,
    },
    accounts: result.accounts.map(a => ({
      role: a.role,
      publicKey: a.publicKey,
      secret: a.secret,
      trustline: a.trustline,
      description: a.description,
      balances: {
        xlm: result.balances[a.role]?.xlm ?? 0,
        usdc: result.balances[a.role]?.usdc ?? 0,
      },
    })),
    datasets: result.datasetIds,
  };
}

export async function writeArtifacts(
  envPath: string,
  accountsPath: string,
  result: ProvisionResult,
): Promise<void> {
  await writeFile(envPath, renderEnvFile(result), 'utf8');
  await writeFile(accountsPath, `${JSON.stringify(renderAccountsFile(result), null, 2)}\n`, 'utf8');
}
